# GGIS 371: Week 1 - Intro to Python
**By: M. Kolak, 2022-01-20**

In the first week's lab, our goal are to get familiar with *applied programming*, using python in the CyberGISX environment. That means creating our first Jupter Notebook! Specific objectives include:

- Setting up a coding environment in CyberGISX
- Learning basic file management
- Subset & filter non-spatial data

By the end, we'll be comfortable with the basics of working with data in a coding notebook. We'll also consider what is *missing* when we aren't leveraging the spatial dimension of the data, and start to brainstorm troubleshooting approaches.

### What if I don't understand everything?
If items come up in the code that you're not sure about -- search it up on Google! Troubleshooting and googling/searching for explanations as you go is crucial to applied programming. Also, keep in mind that you may not have a deep knowledge of every component of every function. But, you should have an understanding of what your *goal* is, inspecting the data you produce regularly to ensure you are *actually* doing what you were planning on doing.

## Getting Started

### Know Your Directory

Do you know what's in your current working directory? In Python, there are a number of ways to check. Try the following, where we load a library called 'os' and use it to identify what's in the current directory, referenced as `"."`. Does this match up with what you see in the CyberGISX panel on the left?

In [86]:
import os
os.listdir(".") # returns list

['Ch3-SpatialData.ipynb', 'data', '.ipynb_checkpoints', 'Ch1-Intro2Py.ipynb']

You should only see data that's in *your* folder; what's shown above is what was in *my* folder. If you're not in a folder that includes the notebook you're working on (`.ipnyb` file), or a folder of the data for our lab, you're in the wrong spot. For now, navigate to the right place in CyberGISX manually. Then, check back here.

### Check a folder's content

Let's see what the contents of the 'data folder are.

In [87]:
os.listdir("./data") #

['tokyo_clean.csv',
 'airports1.csv',
 'airports.csv',
 '.ipynb_checkpoints',
 'tokyo.gpkg',
 'countries_clean.gpkg',
 'airports.gpkg']

You should see the `airport.csv` dataset. If you do, you're ready for the nexts step! If not, troubleshoot.

***

## Environment Setup

First, we will load libraries for our work. This week we're leveraging Pandas, a powerful libray for working with data.

In [91]:
import pandas

### Data Import

Let's bring some data into our coding environment for practice. We will be using airport data, saved as a CSV file, provided for this lab.

- `airport.csv`

First, make sure the data for this lab is uploaded into a folder called "data" in your GGIS 371 folder on CyberGISX. Navigate in the CyberGISX console, and confirm! This is a dataset from 2009 that is a detailed GIS compilation of world wide airports that is in the public domain (more info [here](https://www.naturalearthdata.com/downloads/10m-cultural-vectors/airports/)).

### Read & Inspect Data
Next, let's use `pandas` to read in our CSV file, using `read_csv`.

In [92]:
airports = pandas.read_csv("./data/airports.csv")

Immediately, we'll want to look at the data to confirm it's what we expected. We use the `head` function to read the first five rows of data.

In [15]:
airports.head()

,scalerank,featurecla,type,name,abbrev,location,gps_code,iata_code,wikipedia,natlscale,...,name_tr,name_vi,name_zh,wdid_score,ne_id,name_fa,name_he,name_uk,name_ur,name_zht
0,9,Airport,small,Sahnewal,LUH,terminal,VILD,LUH,http://en.wikipedia.org/wiki/Sahnewal_Airport,8.0,...,,,,4.0,1159113785,فرودگاه سهنول,,,,
1,9,Airport,mid,Solapur,SSE,terminal,VASL,SSE,http://en.wikipedia.org/wiki/Solapur_Airport,8.0,...,,,,4.0,1159113803,فرودگاه سولاپور,,,,
2,9,Airport,mid,Birsa Munda,IXR,terminal,VERC,IXR,http://en.wikipedia.org/wiki/Birsa_Munda_Airport,8.0,...,Birsa Munda Havaalanı,Sân bay Birsa Munda,比尔萨·蒙达机场,4.0,1159113831,فرودگاه بیرسا موندا,,,,比爾薩·蒙達機場
3,9,Airport,mid,Ahwaz,AWZ,terminal,OIAW,AWZ,http://en.wikipedia.org/wiki/Ahwaz_Airport,8.0,...,Ahvaz Havalimanı,Sân bay Ahvaz,阿瓦士机场,4.0,1159113845,فرودگاه بین المللی اهواز,,,,阿瓦士機場
4,9,Airport,mid and military,Gwalior,GWL,terminal,VIGR,GWL,http://en.wikipedia.org/wiki/Gwalior_Airport,8.0,...,,Sân bay Gwalior,辛迪亚航空站,4.0,1159113863,فرودگاه گوالیور,,,,辛迪亞航空站

### Check Dimensions

We can use the `shape` function to check how many rows and columns exist in the dataset. From this, we can learn that for this dataset, we have 893 airports with 40 columns or attributes of information for each airport.

In [101]:
airports.shape

(893, 40)

***
## Subset Data

A common task for us will be subsetting data, or taking a component of the bigger dataset. 

Let's say we want a data frame with only information about the type of airport, name, it's abbreviation, and code. We'll give it a new name.

In [94]:
airports1 = airports[["name","type","abbrev","natlscale"]]

In [95]:
airports1.head()

          name              type abbrev  natlscale
0     Sahnewal             small    LUH        8.0
1      Solapur               mid    SSE        8.0
2  Birsa Munda               mid    IXR        8.0
3        Ahwaz               mid    AWZ        8.0
4      Gwalior  mid and military    GWL        8.0

### How many categories?
We can see that there are a few different types of airports in the dataset. How many types? We can use `describe` for the basic information about the data.

In [49]:
print(airports1['type'].describe())

count     893
unique      9
top       mid
freq      475
Name: type, dtype: object

### Which categories?
What are the specific data cateogries that we have for airports? We can use the `unique` function for that info.

In [50]:
print(airports1['type'].unique())

['small' 'mid' 'mid and military' 'major and military' 'military mid'
 'military' 'major' 'military major' 'spaceport']

***

## Filter Data
Sometimes we may want to set conditions to filter the data. That could mean, for example: subsetting to only small airports, or only including aiports that have a low national scale. 

### Select By Attribute
In the non-spatial world, we are generally limited to selecting by attribute. That means we can only use the data we see in the table, working the attributes of data. 

Let's start with an example where filter by a category, like only grabbing airports that are small.

In [61]:
smallAirports = airports1[airports1["type"] == 'small']
smallAirports.head()

        name   type abbrev  natlscale
0   Sahnewal  small    LUH        8.0
25   Dhamial  small   OPQS        8.0

Note that we use two equal signs to correspond to the boolean logic "is equal to" -- this may be new to you! In the result, we only have 2 small airports in a our dataset.

Next, let's grab airpots that have a national scale that is above 9.0.

In [96]:
hiScaleAiports = airports1[airports1["natlscale"] < 9]
hiScaleAiports.head()

          name              type abbrev  natlscale
0     Sahnewal             small    LUH        8.0
1      Solapur               mid    SSE        8.0
2  Birsa Munda               mid    IXR        8.0
3        Ahwaz               mid    AWZ        8.0
4      Gwalior  mid and military    GWL        8.0

### Contextualize

How many airports had high scales? We could determine the total rows in our highly scaled airport dataset first, and compare that to the total number of airports we stated with. What are some additional factors you may want to consider? Consider going back a step to re-filter using different logic.

In [97]:
hiScaleAiports.shape

(33, 4)

***

## Write Data
We often will want to export our data when done. This completes the I/O process of data science where we input data, wrangle & run analyses, and the output the products we need. In this intro tutorial, we can keep things simple.

Let's output the cleaned `airport1` data frame we generated earlier as a CSV file. We will output the data into our data folder.

In [74]:
airports1.to_csv("./data/airports1.csv", index=False)

Download the file from CyberGISX to your computer. Open in a software like Excel, Numbers, or GeoDa, and explore!

***

## Dive Deeper

If you started with more Python experience already, and/or want to dive in deeper, here are challenges for you.

- **Skilled up Data Summaries**: There are so many different ways to inspect data! Try searching for and testing out various options for exploring the data you are producing in more depth. Try out data summaries, data plots, and more -- if it doesn't work the first time, don't give up! 
- **Intermediate I/O**: Following steps at the Geocomputation in Python text [linked here](https://py.geocompx.org/07-read-write), load the zip file of airports directly from a URL. Unpackage the zip file in your Python environment, and then work with the data as shown above. You can either keep the spatial data format and work with the attributes directly, or, drop the spatial geometry and work with airport data as a non-spatial data frame.

- **AI Assist**: Using GenAI and/or constructive Googling, generate code for & visualize airport scores from your dataset. What libraries were used? Are there any steps that you're not sure about, or would want to tease out further? Are you able to change the color palette or other features in styling?

### Resources
Some additional resources for further readings:
- [How do I select a subset of a DataFrame?](https://pandas.pydata.org/docs/getting_started/intro_tutorials/03_subset_data.html) - Pandas Documentation